//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int action_user_id { get; set; }
        public int action_type_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> role_id { get; set; }
        public bool readed { get; set; }
        public System.DateTime created_date { get; set; }
    }
}
