//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRole
    {
        public int id { get; set; }
        public int role_id { get; set; }
        public int project_id { get; set; }
        public int numb { get; set; }
    }
}
