//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string about_me { get; set; }
        public string postal_code { get; set; }
        public string avatar { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> district_id { get; set; }
        public Nullable<int> role1 { get; set; }
        public Nullable<int> role2 { get; set; }
        public System.DateTime created_date { get; set; }
    }
}
